services:
  backend:
    image: ${LOCAL_IMAGE_NAME:-stream-model-duration:latest}
    ports:
      - "8180:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=ride_predictions
      - TEST_RUN=False
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-dummy}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-dummy}
      - KINESIS_ENDPOINT_URL=http://kinesis:4566
    env_file:
      - ../src/.env
    depends_on:
      - kinesis

  kinesis:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis
      - DEBUG=1
